@EasyEmployerBackend_HostAddress = http://localhost:5183

### Create Employer
POST {{EasyEmployerBackend_HostAddress}}/api/employer
Content-Type: application/json

{
  "accessToken": "your-access-token-here",
  "werkgevernaam": "Test Employer BV"
}

###
